/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @authors Papaioannou Emmanolia
 *          Lymperis Dimitrios
 *          Chatzhioannou Ioannis
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        setTitle("JokerGame-Stats");
        //Team members names, displayed in random order
        List<String> teamNames = new ArrayList<>();
        teamNames.add("Παπαϊωάννου Εμμανολία");
        teamNames.add("Λυμπέρης Δημήτριος");
        teamNames.add("Χατζηιωάννου Ιωάννης");
        Collections.shuffle(teamNames);
        teamName1.setText(teamNames.get(0));
        teamName2.setText(teamNames.get(1));
        teamName3.setText(teamNames.get(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teamName1 = new javax.swing.JLabel();
        teamName2 = new javax.swing.JLabel();
        teamName3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 400));
        setMinimumSize(new java.awt.Dimension(550, 400));
        setPreferredSize(new java.awt.Dimension(700, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        jLabel2.setText("Η εφαρμογή  JokerGames-Stats υλοποιήθηκε στα πλαίσια");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 470, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        jLabel3.setText("της 3ης  Γραπτής Εργασίας της Θ.Ε. ΠΛΗ24 από ομάδα ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 400, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        jLabel4.setText("του τμήματος ΗΛΕ43. Η εφαρμογή επεξεργάζεται δεδομένα");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 410, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        jLabel5.setText("που λαμβάνει από την υπηρεσία ιστού api.opap.gr/.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        jLabel6.setText("Mέλη ομάδας");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        teamName1.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        teamName1.setText("jLabel7");
        getContentPane().add(teamName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        teamName2.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        teamName2.setText("jLabel8");
        getContentPane().add(teamName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        teamName3.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        teamName3.setText("jLabel9");
        getContentPane().add(teamName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTextField1.setText("JokerGame-Stats");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 140, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Καθηγητής τμήματος ");
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 180, -1));

        jLabel8.setText("Γκουμόπουλος Χρήστος");
        jLabel8.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tzoker_image2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel teamName1;
    private javax.swing.JLabel teamName2;
    private javax.swing.JLabel teamName3;
    // End of variables declaration//GEN-END:variables
}
