/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import org.emmapap.Connect;
import org.emmapap.Draws;
import org.emmapap.PrizeCategory;
import pojo.Draw;
import pojo.Prizecategory;
import pojo.PrizecategoryPK;

import javax.persistence.spi.PersistenceProvider;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @authors Papaioannou Emmanolia 
 *          Limperis Dimitrios 
 *          Catziioannou Ioannis
 */
public class DrawData extends JFrame {

    /**
     * Creates new form DrawData
     */
    public DrawData() {
        initComponents();
        setTitle("Προβολή δεδομένων κλήρωσης ΤΖΟΚΕΡ");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public Draws publicDraw = new Draws();

    //Μέθοδος που ενημερώνει τα δεδομένα μιας κλήρωσης
    public void updateDrawData(Draws draw) {
        this.publicDraw = draw;
    }

    //Μέθοδος που αποθηκεύει δεδομένα σε JTable και Jlabel
    public void UpdateResultTable(Draws draw) {

        //Δημιουργία εγγραφής τύπου resultTable
        DefaultTableModel model = (DefaultTableModel) resultTable.getModel();

        //Δημιουργία μεταβλητών που παίρνουν ως όρισμα τους νικητήριους αριθμούς
        String wn1 = Integer.toString(draw.getWinningNumber1());
        String wn2 = Integer.toString(draw.getWinningNumber2());
        String wn3 = Integer.toString(draw.getWinningNumber3());
        String wn4 = Integer.toString(draw.getWinningNumber4());
        String wn5 = Integer.toString(draw.getWinningNumber5());
        String wn6 = Integer.toString(draw.getBonusNumber());

        //Περνάμε τους νικητήριους αριθμούς στα αντίστοιχα jlabel
        winningNumber1.setText(wn1);
        winningNumber2.setText(wn2);
        winningNumber3.setText(wn3);
        winningNumber4.setText(wn4);
        winningNumber5.setText(wn5);
        bonusNumber.setText(wn6);

        //Περνάμε τον αριθμό κλήρωσης στο drawIdLabel
        drawIdLabel.setFont(new java.awt.Font("Dialog", 1, 15));
        drawIdLabel.setForeground(new java.awt.Color(222, 222, 222));
        drawIdLabel.setText("Aριθμός κλήρωσης: " + draw.getId());

        //Περνάμε τα ζητούμενα δεδομένα στον πίνακα που θα εμφανιστεί στο χρήστη
        for (PrizeCategory prizeCategory : draw.prizeCategories) {
            //Δίνουμε ονόματα στις κατηγορίες επιτυχιών
            prizeCategory.setPrizeCategoryName();
            model.addRow(new Object[]{prizeCategory.getPrizeCategoryName(), prizeCategory.getWinners(), String.valueOf(prizeCategory.getFormatedNumber(prizeCategory.getDivident()))});
        }
        //Επιλογή να ταξινομείται αυτόματα ο πίνακας όταν ο χρήστης πατήσει κάποια επικεφαλίδα
        resultTable.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        bonusNumber = new javax.swing.JLabel();
        circleLabel6 = new javax.swing.JLabel();
        winningNumber3 = new javax.swing.JLabel();
        circleLabel3 = new javax.swing.JLabel();
        winningNumber2 = new javax.swing.JLabel();
        circleLabel2 = new javax.swing.JLabel();
        winningNumber1 = new javax.swing.JLabel();
        circleLabel1 = new javax.swing.JLabel();
        winningNumber4 = new javax.swing.JLabel();
        circleLabel4 = new javax.swing.JLabel();
        winningNumber5 = new javax.swing.JLabel();
        circleLabel5 = new javax.swing.JLabel();
        showDataLabel = new javax.swing.JLabel();
        drawIdLabel = new javax.swing.JLabel();
        saveDataButton = new javax.swing.JButton();
        backgroundLayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultTable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        resultTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Κατηγορίες", "Αριθμός επιτυχιών", "Κέρδη"
            }
        ) {
            final boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 400, 160));

        bonusNumber.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bonusNumber.setForeground(new java.awt.Color(0, 0, 255));
        bonusNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonusNumber.setText("jLabel8");
        bonusNumber.setForeground(new java.awt.Color(0, 0, 255)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        bonusNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bonusNumber.setMaximumSize(new java.awt.Dimension(63, 15));
        bonusNumber.setMinimumSize(new java.awt.Dimension(63, 15));
        bonusNumber.setPreferredSize(new java.awt.Dimension(63, 15));
        getContentPane().add(bonusNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 40, 40));

        circleLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bonus-circle.png"))); // NOI18N
        circleLabel6.setText("jLabel2");
        getContentPane().add(circleLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 40, -1));

        winningNumber3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        winningNumber3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winningNumber3.setText("jLabel7");
        winningNumber3.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        winningNumber3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        winningNumber3.setMaximumSize(new java.awt.Dimension(63, 15));
        winningNumber3.setMinimumSize(new java.awt.Dimension(63, 15));
        winningNumber3.setPreferredSize(new java.awt.Dimension(63, 15));
        getContentPane().add(winningNumber3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 40, 40));

        circleLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winningNumber-circle.png"))); // NOI18N
        circleLabel3.setText("jLabel1");
        getContentPane().add(circleLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 40, -1));

        winningNumber2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        winningNumber2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winningNumber2.setText("jLabel7");
        winningNumber2.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        winningNumber2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        winningNumber2.setMaximumSize(new java.awt.Dimension(63, 15));
        winningNumber2.setMinimumSize(new java.awt.Dimension(63, 15));
        winningNumber2.setPreferredSize(new java.awt.Dimension(63, 15));
        getContentPane().add(winningNumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 40, 40));

        circleLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winningNumber-circle.png"))); // NOI18N
        circleLabel2.setText("jLabel1");
        getContentPane().add(circleLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 40, -1));

        winningNumber1.setFont(new java.awt.Font("Dialog", 1, 11));
        winningNumber1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winningNumber1.setText("1");
        winningNumber1.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        winningNumber1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(winningNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 40, 40));

        circleLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winningNumber-circle.png"))); // NOI18N
        circleLabel1.setText("jLabel1");
        getContentPane().add(circleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 40, 40));

        winningNumber4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        winningNumber4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winningNumber4.setText("jLabel7");
        winningNumber4.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        winningNumber4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        winningNumber4.setMaximumSize(new java.awt.Dimension(63, 15));
        winningNumber4.setMinimumSize(new java.awt.Dimension(63, 15));
        winningNumber4.setPreferredSize(new java.awt.Dimension(63, 15));
        getContentPane().add(winningNumber4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 40, 40));

        circleLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winningNumber-circle.png"))); // NOI18N
        circleLabel4.setText("jLabel1");
        getContentPane().add(circleLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 40, -1));

        winningNumber5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        winningNumber5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winningNumber5.setText("jLabel7");
        winningNumber5.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        winningNumber5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        winningNumber5.setMaximumSize(new java.awt.Dimension(63, 15));
        winningNumber5.setMinimumSize(new java.awt.Dimension(63, 15));
        winningNumber5.setPreferredSize(new java.awt.Dimension(63, 15));
        getContentPane().add(winningNumber5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 40, 40));

        circleLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winningNumber-circle.png"))); // NOI18N
        circleLabel5.setText("jLabel1");
        getContentPane().add(circleLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 40, -1));

        showDataLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showDataLabel.setText("Προβολή δεδομένων ");
        showDataLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        getContentPane().add(showDataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 210, 50));

        drawIdLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        drawIdLabel.setText("jLabel1");
        drawIdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(drawIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        saveDataButton.setBackground(new java.awt.Color(49, 144, 226));
        saveDataButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        saveDataButton.setForeground(new java.awt.Color(0, 0, 0));
        saveDataButton.setText("Αποθήκευση Κλήρωσης");
        saveDataButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveDataButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 140, 30));

        backgroundLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tzoker_image2.jpg"))); // NOI18N
        backgroundLayer.setText("Game Id:");
        backgroundLayer.setFocusCycleRoot(true);
        backgroundLayer.setPreferredSize(new java.awt.Dimension(575, 435));
        getContentPane().add(backgroundLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataButtonActionPerformed
        //Εκκίνηση server για τη ΒΔ
        //Connect con = new Connect();
        //con.connect();

        //Δημιουργία του EntityManagerFactory
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokerGameStatsPU");
        //Δημιουργία του EntityManager
        EntityManager em = emf.createEntityManager();

        //Έναρξη διαδικασίας προσπάθειας αποθήκευσης δεδομένων στη βάση δεδομένων
        try {
            //Έναρξη δοσοληψίας με τη βάση δεδομένων
            em.getTransaction().begin();
            Query findDraw = em.createNamedQuery("Draw.findById", Draw.class);
            findDraw.setParameter("id", publicDraw.getId());
            List<Draw> resultList = findDraw.getResultList();

            //Aν τα επιλεγμένα δεδομένα δεν υπάρχουν ήδη στη βάση δεδομένων
            if (resultList.isEmpty()) {

                //Aποθήκευση δεδομένων στον πίνακα Draw στη βάση δεδομένων
                java.sql.Date sqlDate = new java.sql.Date(publicDraw.getDrawTime());//Mετατροπή ημερομηνίας σε μορφή ημερομηνίας που αναγνωρίζει η βάση δεδομένων
                Draw drawEntity = new Draw(publicDraw.getId(), sqlDate, publicDraw.getWinningNumber1(),
                        publicDraw.getWinningNumber2(), publicDraw.getWinningNumber3(), publicDraw.getWinningNumber4(),
                        publicDraw.getWinningNumber5(), publicDraw.getBonusNumber());
                em.persist(drawEntity);

                //Αποθήκευση δεδομένων στον πίνακα Prizecategory στη βάση δεδομένων
                for (PrizeCategory prc : publicDraw.prizeCategories) {
                    Prizecategory prizeCategory = new Prizecategory();
                    PrizecategoryPK prizeCategoryPK = new PrizecategoryPK();
                    prizeCategoryPK.setId(prc.getPrizeCategoryId());
                    prizeCategoryPK.setDrawid(prc.getDrawId());
                    prizeCategory.setDraw(drawEntity);
                    prizeCategory.setName(prc.getPrizeCategoryName());
                    prizeCategory.setWinners(prc.getWinners());
                    prizeCategory.setDivident(prc.getDivident());
                    prizeCategory.setPrizecategoryPK(prizeCategoryPK);
                    em.persist(prizeCategory);
                }

                //Τερματισμός δοσοληψίας
                em.getTransaction().commit();
                //Ενημερωτικό μήνυμα ότι τα δεδομένα αποθηκεύτηκαν επιτυχώς
                JOptionPane.showMessageDialog(null, "Η κλήρωση αποθηκεύτηκε επιτυχώς στη βάση δεδομένων. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                //Aν τα επιλεγμένα δεδομένα υπάρχουν ήδη στη βάση δεδομένων
            } else {
                //Τερματισμός δοσοληψίας
                em.getTransaction().commit();
                //Εμφάνισε ενημερωτικό μήνυμα
                JOptionPane.showMessageDialog(null, "Tα δεδομένα που επιλέξατε υπάρχουν ήδη στη βάση δεδομένων. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            //Ενημερωτικό μήνυμα ότι δεν ήταν επιτυχής η σύνδεση με τη βάση δεδομένων
            JOptionPane.showMessageDialog(null, "Η αποθήκευση της κλήρωσης δεν ήταν επιτυχής. Προσπαθήστε ξανά.  ", "Πρόβλημα σύνδεσης με βάση δεδομένων", JOptionPane.INFORMATION_MESSAGE);
        }

        //Καταστροφή του EntityManager
        em.close();
        //Καταστροφή του EntityManagerFactory
        emf.close();
        //con.disconnect();
    }//GEN-LAST:event_saveDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawData().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLayer;
    private javax.swing.JLabel bonusNumber;
    private javax.swing.JLabel circleLabel1;
    private javax.swing.JLabel circleLabel2;
    private javax.swing.JLabel circleLabel3;
    private javax.swing.JLabel circleLabel4;
    private javax.swing.JLabel circleLabel5;
    private javax.swing.JLabel circleLabel6;
    private javax.swing.JLabel drawIdLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton saveDataButton;
    private javax.swing.JLabel showDataLabel;
    private javax.swing.JLabel winningNumber1;
    private javax.swing.JLabel winningNumber2;
    private javax.swing.JLabel winningNumber3;
    private javax.swing.JLabel winningNumber4;
    private javax.swing.JLabel winningNumber5;
    // End of variables declaration//GEN-END:variables
}
