/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @authors Papaioannou Emmanolia 
 *          Limperis Dimitrios 
 *          Chatziioannou Ioannis
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setTitle("JokerGame-Stats");
        addWindowListener(new WindowAdapter() {
            //Eνημερωτικό μήνυμα όταν ο χρήστης κλείνει την εφαρμογή
            @Override
            public void windowClosing(WindowEvent evt) {
                int result = JOptionPane.showConfirmDialog(null,
                        "Η εφαρμογή θα τερματιστεί. Είστε σίγουροι;", "Τερματισμός εφαρμογής",
                        JOptionPane.YES_NO_OPTION);

                if (JOptionPane.YES_OPTION == result) {
                    //Kαταστροφή παραθύρου
                    dispose();
                    //Τερματισμός
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jokerLabel = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        manageDataButton = new javax.swing.JButton();
        showDataButton = new javax.swing.JButton();
        showStatisticsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        returnHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(610, 429));
        setResizable(false);

        jokerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tzoker_kentriki.jpg"))); // NOI18N
        jokerLabel.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        homePanel.setBackground(new java.awt.Color(125, 173, 216));

        manageDataButton.setBackground(new java.awt.Color(49, 144, 226));
        manageDataButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        manageDataButton.setForeground(new java.awt.Color(0, 0, 0));
        manageDataButton.setText("Διαχείριση δεδομένων");
        manageDataButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDataButtonActionPerformed(evt);
            }
        });

        showDataButton.setBackground(new java.awt.Color(49, 144, 226));
        showDataButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        showDataButton.setForeground(new java.awt.Color(0, 0, 0));
        showDataButton.setText("  Προβολή δεδομένων  ");
        showDataButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showDataButton.setPreferredSize(new java.awt.Dimension(153, 25));
        showDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataButtonActionPerformed(evt);
            }
        });

        showStatisticsButton.setBackground(new java.awt.Color(49, 144, 226));
        showStatisticsButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        showStatisticsButton.setForeground(new java.awt.Color(0, 0, 0));
        showStatisticsButton.setText("Προβολή στατιστικών δεδομένων");
        showStatisticsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStatisticsButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(49, 144, 226));
        exitButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Έξοδος");
        exitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        returnHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        returnHomeButton.setBorder(null);
        returnHomeButton.setBorderPainted(false);
        returnHomeButton.setContentAreaFilled(false);
        returnHomeButton.setFocusPainted(false);
        returnHomeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about2.png"))); // NOI18N
        returnHomeButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about2.png"))); // NOI18N
        returnHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnHomeButton)
                .addGap(58, 58, 58)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showStatisticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showDataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(manageDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(showDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(showStatisticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnHomeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jokerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jokerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataButtonActionPerformed
        //Δημιούργησε ένα αντικείμενο τύπου ShowDataPerMonth
        ShowDataPerMonth showData = new ShowDataPerMonth();
        //Κάνε το αντικείμενο showData ορατό (Οθόνη Προβολής δεδομένων ανά μήνα)
        showData.setVisible(true);
        //Κάνε το παράθυρο home όχι ορατό
        this.setVisible(false);
        //Κλείσε το παράθυρο home
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        //Κατέστρεψε το παράθυρο home
        this.dispose();
    }//GEN-LAST:event_showDataButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        //Eνημερωτικό μήνυμα προς χρήστη
        int result = JOptionPane.showConfirmDialog(null, "Η εφαρμογή θα τερματιστεί. Είστε σίγουροι;", "Ενημέρωση", JOptionPane.YES_NO_OPTION);

        //Aν ο χρήστης επιβεβαιώσει τον τερματισμό
        if (JOptionPane.YES_OPTION == result) {
            //Καταστροφή παραθύρου
            dispose();
            //Τερματισμός
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void manageDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDataButtonActionPerformed
        //Δημιούργησε ένα αντικείμενο τύπου ManageData
        ManageData manageData = new ManageData();
        //Κάνε το αντικείμενο τύπου ManageData ορατό (Οθόνη Διαχείρισης δεδομένων)
        manageData.setVisible(true);
        //Κάνε το παράθυρο home όχι ορατό
        this.setVisible(false);
        //Κλείσε το παράθυρο home
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        //Κατέστρεψε το παράθυρο home
        this.dispose();
    }//GEN-LAST:event_manageDataButtonActionPerformed

    private void showStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStatisticsButtonActionPerformed
        //Δημιούργησε ένα αντικείμενο τύπου ShowStatistics
        ShowStatistics showStatistics = new ShowStatistics();
        //Κάνε το αντικείμενο τύπου showStatistics ορατό (Οθόνη προβοληλής στατιστικών στοιχείων)
        showStatistics.setVisible(true);
        //Κάνε το παράθυρο home όχι ορατό
        this.setVisible(false);
        //Κλείσε το παράθυρο home
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        //Κατέστρεψε το παράθυρο home
        this.dispose();
    }//GEN-LAST:event_showStatisticsButtonActionPerformed

    private void returnHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeButtonActionPerformed
        //Δημιούργησε ένα αντικείμενο τύπου Home
        About about = new About();
        //Κάνε το αντικείμενο τύπου Home ορατό (Επιστροφή στην αρχική οθόνη)
        about.setVisible(true);

    }//GEN-LAST:event_returnHomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                home.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jokerLabel;
    private javax.swing.JButton manageDataButton;
    private javax.swing.JButton returnHomeButton;
    private javax.swing.JButton showDataButton;
    private javax.swing.JButton showStatisticsButton;
    // End of variables declaration//GEN-END:variables
}
