/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import com.google.gson.*;
import org.emmapap.DateValidator;
import org.emmapap.DateValidatorUsingDateFormat;
import org.emmapap.Draws;
import org.emmapap.PrizeCategory;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import pojo.Draw;

import javax.persistence.*;
import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 *
 * @authors Papaioannou Emmanolia 
 *          Lymperis Dimitrios 
 *          Chatziioannou Ioannis
 */
public class ManageData extends javax.swing.JFrame {

    /**
     * Creates new form ManageData
     */
    //Construct an object of type Draws to pass the draw data
    public Draws draw = new Draws();

    public ManageData() {
        initComponents();
        setTitle("JokerGame-Stats");
        addWindowListener(new WindowAdapter() {
            //Eνημερωτικό μήνυμα όταν ο χρήστης κλείνει την εφαρμογή
            @Override
            public void windowClosing(WindowEvent evt) {
                int result = JOptionPane.showConfirmDialog(null,
                        "Η εφαρμογή θα τερματιστεί. Είστε σίγουροι;", "Τερματισμός εφαρμογής",
                        JOptionPane.YES_NO_OPTION);

                if (JOptionPane.YES_OPTION == result) {
                    dispose();
                    System.exit(0);
                }
            }
        });

        GameIdComboBox.setMaximumRowCount(6); //Max lines combobox 6
        FromDateComboBox.setMaximumRowCount(6); //Max lines combobox 6
        ToDateComboBox.setMaximumRowCount(6); //Max lines combobox 6

        //Variables that store the dates for 2000-01-01 and today
        LocalDate startDate = LocalDate.of(2000, 01, 01);
        LocalDate endDate = LocalDate.now();
        long numOfDays = ChronoUnit.DAYS.between(startDate, endDate);

        //For the years 2000 to 2022 make a list of dates
        List<LocalDate> listOfDates1 = Stream.iterate(startDate, date -> date.plusDays(1))
                .limit(numOfDays + 1)
                .collect(Collectors.toList());

        //Add dates to ToDateCombobox and ToDateComboBox1
        for (int i = 0; i < listOfDates1.size(); i++) {
            ToDateComboBox.addItem(listOfDates1.get(i).toString());
            ToDateComboBox1.addItem(listOfDates1.get(i).toString());
        }

        //Add dates to FromDateCombobox and FromDateCombobox1
        for (int i = 0; i < listOfDates1.size(); i++) {
            FromDateComboBox.addItem(listOfDates1.get(i).toString());
            FromDateComboBox1.addItem(listOfDates1.get(i).toString());
        }

        //Make the initial selection of the following comboboxes null
        GameIdComboBox.setSelectedItem(null);
        FromDateComboBox.setSelectedItem(null);
        ToDateComboBox.setSelectedItem(null);
        FromDateComboBox1.setSelectedItem(null);
        ToDateComboBox1.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnHomeButton = new javax.swing.JButton();
        manageDataLabel = new javax.swing.JLabel();
        GameIdComboBox = new javax.swing.JComboBox<>();
        gameIdLabel = new javax.swing.JLabel();
        fromDateLabel = new javax.swing.JLabel();
        toDateLabel = new javax.swing.JLabel();
        FromDateComboBox = new javax.swing.JComboBox<>();
        ToDateComboBox = new javax.swing.JComboBox<>();
        SearchDrawIdButton = new javax.swing.JButton();
        SearchDateButton = new javax.swing.JButton();
        deleteGameDataFromDateToDateButton = new javax.swing.JButton();
        deleteGameDataButton = new javax.swing.JButton();
        fromDateLabel1 = new javax.swing.JLabel();
        toDateLabel1 = new javax.swing.JLabel();
        GameIdComboBox1 = new javax.swing.JComboBox<>();
        FromDateComboBox1 = new javax.swing.JComboBox<>();
        ShowDataDateButton = new javax.swing.JButton();
        gameIdLabel1 = new javax.swing.JLabel();
        ToDateComboBox1 = new javax.swing.JComboBox<>();
        backgroundLayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 570));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnHomeButton.setBackground(returnHomeButton.getBackground());
        returnHomeButton.setForeground(returnHomeButton.getBackground());
        returnHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1_1.png"))); // NOI18N
        returnHomeButton.setBorder(null);
        returnHomeButton.setBorderPainted(false);
        returnHomeButton.setContentAreaFilled(false);
        returnHomeButton.setFocusPainted(false);
        returnHomeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1click.png"))); // NOI18N
        returnHomeButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1click.png"))); // NOI18N
        returnHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 60));

        manageDataLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageDataLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        manageDataLabel.setText("Διαχείριση δεδομένων ");
        getContentPane().add(manageDataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, 50));

        GameIdComboBox.setBackground(new java.awt.Color(222, 222, 222));
        GameIdComboBox.setEditable(true);
        getContentPane().add(GameIdComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 160, -1));

        gameIdLabel.setBackground(backgroundLayer.getBackground());
        gameIdLabel.setForeground(new java.awt.Color(222, 222, 222));
        gameIdLabel.setLabelFor(GameIdComboBox);
        gameIdLabel.setText("Κωδικός κλήρωσης:");
        gameIdLabel.setToolTipText("");
        getContentPane().add(gameIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 20));

        fromDateLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων
        fromDateLabel.setLabelFor(FromDateComboBox);
        fromDateLabel.setText("Από:");
        getContentPane().add(fromDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, 20));

        toDateLabel.setLabelFor(ToDateComboBox);
        toDateLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        toDateLabel.setText("Εώς:");
        getContentPane().add(toDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, 20));

        FromDateComboBox.setBackground(new java.awt.Color(222, 222, 222));
        FromDateComboBox.setEditable(true);
        getContentPane().add(FromDateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 160, -1));

        ToDateComboBox.setBackground(new java.awt.Color(222, 222, 222));
        ToDateComboBox.setEditable(true);
        getContentPane().add(ToDateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 160, -1));

        SearchDrawIdButton.setBackground(new java.awt.Color(49, 144, 226));
        SearchDrawIdButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        SearchDrawIdButton.setText("Προβολή δεδομένων");
        SearchDrawIdButton.setForeground(new java.awt.Color(0, 0, 0));
        SearchDrawIdButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchDrawIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDrawIdButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchDrawIdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, 30));

        SearchDateButton.setBackground(new java.awt.Color(49, 144, 226));
        SearchDateButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        SearchDateButton.setText("Αναζήτηση");
        SearchDateButton.setForeground(new java.awt.Color(0, 0, 0));
        SearchDateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchDateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 30));

        deleteGameDataFromDateToDateButton.setBackground(new java.awt.Color(49, 144, 226));
        deleteGameDataFromDateToDateButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        deleteGameDataFromDateToDateButton.setText(" Διαγραφή δεδομένων κληρώσεων εντός εύρους ημερομηνιών ");
        deleteGameDataFromDateToDateButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteGameDataFromDateToDateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteGameDataFromDateToDateButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deleteGameDataFromDateToDateButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        deleteGameDataFromDateToDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGameDataFromDateToDateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteGameDataFromDateToDateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, 30));

        deleteGameDataButton.setBackground(new java.awt.Color(49, 144, 226));
        deleteGameDataButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        deleteGameDataButton.setText("Διαγραφή δεδομένων κλήρωσης");
        deleteGameDataButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteGameDataButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteGameDataButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteGameDataButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        deleteGameDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGameDataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteGameDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, 30));

        fromDateLabel1.setLabelFor(FromDateComboBox);
        fromDateLabel1.setText("Από:");
        fromDateLabel1.setForeground(new java.awt.Color(222, 222, 222));
        getContentPane().add(fromDateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, 20));

        toDateLabel1.setLabelFor(ToDateComboBox);
        toDateLabel1.setText("Εώς:");
        toDateLabel1.setForeground(new java.awt.Color(222, 222, 222));
        getContentPane().add(toDateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, 20));

        GameIdComboBox1.setBackground(new java.awt.Color(222, 222, 222));
        GameIdComboBox1.setEditable(true);
        getContentPane().add(GameIdComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 160, -1));

        FromDateComboBox1.setBackground(new java.awt.Color(222, 222, 222));
        FromDateComboBox1.setEditable(true);
        getContentPane().add(FromDateComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 160, -1));

        ShowDataDateButton.setBackground(new java.awt.Color(49, 144, 226));
        ShowDataDateButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ShowDataDateButton.setText("Προβολή δεδομένων");
        ShowDataDateButton.setForeground(new java.awt.Color(0, 0, 0));
        ShowDataDateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ShowDataDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDataDateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowDataDateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, 30));

        gameIdLabel1.setBackground(backgroundLayer.getBackground());
        gameIdLabel1.setLabelFor(GameIdComboBox);
        gameIdLabel1.setText("Κωδικός κλήρωσης:");
        gameIdLabel1.setForeground(new java.awt.Color(222, 222, 222));
        gameIdLabel1.setToolTipText("");
        getContentPane().add(gameIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 20));

        ToDateComboBox1.setBackground(new java.awt.Color(222, 222, 222));
        ToDateComboBox1.setEditable(true);
        getContentPane().add(ToDateComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 160, -1));

        backgroundLayer.setForeground(backgroundLayer.getBackground());
        backgroundLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tzoker_image2.jpg"))); // NOI18N
        backgroundLayer.setText("Game Id:");
        backgroundLayer.setFocusCycleRoot(true);
        backgroundLayer.setPreferredSize(new java.awt.Dimension(575, 435));
        getContentPane().add(backgroundLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -270, 830, 1010));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_returnHomeButtonActionPerformed

    private void deleteGameDataFromDateToDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGameDataFromDateToDateButtonActionPerformed
        //If the user has not entered dates
        if ((FromDateComboBox1.getSelectedItem() == null) || (ToDateComboBox1.getSelectedItem() == null)) {
            //Informative message
            JOptionPane.showMessageDialog(null, "Πρέπει να εισάγετε εύρος ημερομηνιών.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //Check if date is in correct format
        DateValidator validator = new DateValidatorUsingDateFormat("yyyy-mm-dd");
        if (!validator.isValid(FromDateComboBox1.getSelectedItem().toString()) || !validator.isValid(ToDateComboBox1.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Οι ημερομηνίες δεν είναι σε σωστή μορφή (εεεε-μμ-ηη).", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //Check if the date is valid (eg 2022-02-30 is an invalid date)
        try {
            LocalDate fromDate = LocalDate.parse(FromDateComboBox1.getSelectedItem().toString());
            LocalDate toDate = LocalDate.parse(ToDateComboBox1.getSelectedItem().toString());

            //Check if the entered dates are until today
            if (LocalDate.now().isBefore(fromDate) || LocalDate.now().isBefore(toDate)) {
                JOptionPane.showMessageDialog(null, "Έχετε εισάγει ημερομηνίες που ξεπερνούν τη σημερινή ημέρα. Προσπαθήστε ξανά.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Μη έγκυρη ημερομηνία.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            //Clean ComboBox from invalid values
            ToDateComboBox1.setSelectedItem(null);
            FromDateComboBox1.setSelectedItem(null);
            return;
        }

        //Calculate how many days in total the user has selected. If the result is negative, the user has put the dates in the wrong order
        LocalDate fromDate = LocalDate.parse(FromDateComboBox1.getSelectedItem().toString());
        LocalDate toDate = LocalDate.parse(ToDateComboBox1.getSelectedItem().toString());
        long fromDateDays = fromDate.toEpochDay();
        long toDateDays = toDate.toEpochDay();
        long duration = toDateDays - fromDateDays + 1;

        //Informative message to the user in case the fromDate date is greater than the toDate date
        if (duration < 0) {
            JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή εύρους ημερομηνιών. Προσπαθήστε ξανά. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //Show window to user to confirm deletion of draws
        int result = JOptionPane.showConfirmDialog(null, "Tο σύστημα θα διαγράψει από τη βάση δεδομένων όλα τα δεδομένα των κληρώσεων από " + FromDateComboBox1.getSelectedItem()
                + " έως " + ToDateComboBox1.getSelectedItem() + ".\nΕίστε σίγουροι;", "Διαγραφή Δεδομένων Κλήρωσης", JOptionPane.YES_NO_OPTION);

        //If the user clicks accept delete data
        if (JOptionPane.YES_OPTION == result) {
            System.out.println("ΑΠΟΔΟΧΗ ΔΙΑΓΡΑΦΗΣ ΔΕΔΟΜΕΝΩΝ ΕΝΤΟΣ ΕΥΡΟΥΣ ΗΜΕΡΟΜΗΝΙΩΝ");


            EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokerGameStatsPU");
            EntityManager em = emf.createEntityManager();

            //Attempt to start transaction with database
            try {
                //Start transaction
                em.getTransaction().begin();
                //Create database query to delete all data from Draw table in given date range
                Query findDraws = em.createNativeQuery("DELETE FROM DRAW WHERE DATE BETWEEN '" + FromDateComboBox1.getSelectedItem().toString() + "' AND '"
                        + ToDateComboBox1.getSelectedItem().toString() + "'");

                //Delete from the Draw table all data in a certain date range (they are automatically deleted from the Prizecategory table as well)
                findDraws.executeUpdate();

                //End transaction
                em.getTransaction().commit();
                //Display informational message
                JOptionPane.showMessageDialog(null, "Όσες κληρώσεις υπήρχαν από " + FromDateComboBox1.getSelectedItem().toString() + " έως "
                        + ToDateComboBox1.getSelectedItem().toString() + " διαγράφηκαν επιτυχώς από τη βάση δεδομένων. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                //Failed to connect to the database
            } catch (Exception e) {
                //Display an informational message that no deletion took place
                JOptionPane.showMessageDialog(null, "Η διαγραφή δεν ήταν επιτυχής. Προσπαθήστε ξανά.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            }

            //Καταστροφή EntityManagerFactory και EntityManager
            em.close();
            emf.close();

        } //If the user does not accept the deletion of data
        else if (JOptionPane.NO_OPTION == result) {
            System.out.println("MH ΑΠΟΔΟΧΗ ΔΙΑΓΡΑΦΗΣ ΔΕΔΟΜΕΝΩΝ ΕΝΤΟΣ ΕΥΡΟΥΣ ΗΜΕΡΟΜΗΝΙΩΝ");
        } //If the user closes the window
        else
        {
            System.out.println("ΚΛΕΙΣΙΜΟ ΠΑΡΑΘΥΡΟΥ");
        }
    }//GEN-LAST:event_deleteGameDataFromDateToDateButtonActionPerformed

    private void SearchDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDateButtonActionPerformed
        //Search result with date range

        //Clear, if any, the drawIdComboBox data
        GameIdComboBox.removeAllItems();
        //If the user has entered dates
        if (((FromDateComboBox.getSelectedItem() != null) && (ToDateComboBox.getSelectedItem() != null))) {

            //Check if date is in correct format
            DateValidator validator = new DateValidatorUsingDateFormat("yyyy-mm-dd");
            if (!validator.isValid(FromDateComboBox.getSelectedItem().toString()) || !validator.isValid(ToDateComboBox.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "Οι ημερομηνίες δεν είναι σε σωστή μορφή (εεεε-μμ-ηη).", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            //Check if the date is valid (eg 2022-02-30 is an invalid date)
            try {
                LocalDate fromDate = LocalDate.parse(FromDateComboBox.getSelectedItem().toString());
                LocalDate toDate = LocalDate.parse(ToDateComboBox.getSelectedItem().toString());

                //Check if the entered dates are up to date
                if (LocalDate.now().isBefore(fromDate) || LocalDate.now().isBefore(toDate)) {
                    JOptionPane.showMessageDialog(null, "Έχετε εισάγει ημερομηνίες που ξεπερνούν τη σημερινή ημέρα. Προσπαθήστε ξανά.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(null, "Μη έγκυρη ημερομηνία.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            //We calculate from how many days the user chooses to get information from because he can get information up to 3 months (94 days)
            LocalDate fromDate = LocalDate.parse(FromDateComboBox.getSelectedItem().toString());
            LocalDate toDate = LocalDate.parse(ToDateComboBox.getSelectedItem().toString());
            long fromDateDays = fromDate.toEpochDay();
            long toDateDays = toDate.toEpochDay();
            long duration = toDateDays - fromDateDays + 1;

            //Informative message to the user in case the fromDate date is greater than the toDate date
            if (duration < 0) {
                JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή εύρους ημερομηνιών. Προσπαθήστε ξανά. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            //Initialize the timezone because we will need it in date conversions
            ZoneId defaultZoneId = ZoneId.systemDefault();
            //Create a list of Draw objects to store the data we pull from the json

            //If the date range entered by the user exceeds 94 days
            //url returns no data
            //So we "break" the dates into chunks and call the url to fetch data per "chunk"
            while (duration > 94) {
                toDate = fromDate.plusDays(93);
                Date dateTo = Date.from(toDate.atStartOfDay(defaultZoneId).toInstant());
                Date dateFrom = Date.from(fromDate.atStartOfDay(defaultZoneId).toInstant());
                String pattern = "yyyy-MM-dd";
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                String df = simpleDateFormat.format(dateFrom);
                String dt = simpleDateFormat.format(dateTo);

                //Procedure to call url
                //We pass the url to be called to a string
                String urlToCall = "https://api.opap.gr/draws/v3.0/5104/draw-date/" + df + "/" + dt + "/draw-id";
                OkHttpClient client = new OkHttpClient();

                Request request = new Request.Builder().url(urlToCall).build();

                //Call the appropriate url
                try (Response response = client.newCall(request).execute()) {
                    if (response.isSuccessful() && response.body() != null) {
                        String responseString = response.body().string();

                        //Process to extract the Json data
                        //Create a GsonBuilder object
                        GsonBuilder builder = new GsonBuilder();
                        Gson gson = builder.create();
                        //Get the results into a JsonArray
                        JsonArray json = gson.fromJson(responseString, JsonArray.class);

                        //Pass the data from JsonArray to GameIdComboBox
                        for (int i = 0; i < json.size(); i++) {
                            GameIdComboBox.addItem(json.get(i).toString());
                        }

                        //Calculate the new dates for which Url will be called
                        duration = duration - 94;
                        fromDate = toDate.plusDays(1);
                        if (duration == 0) {
                            break;
                        } else if (duration < 95) {
                            toDate = toDate.plusDays(duration);
                        }

                    } else {
                        //Informative message in case of incorrect date input (FromDate>ToDate)
                        JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή ημερομηνιών. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Πρόβλημα κλήσης URL. Προσπαθήστε ξανά.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            //If there are days left when we didn't pull data recalculate dates and callback url
            if (duration > 0 && duration < 95) {
                Date dateTo = Date.from(toDate.atStartOfDay(defaultZoneId).toInstant());
                Date dateFrom = Date.from(fromDate.atStartOfDay(defaultZoneId).toInstant());
                String pattern = "yyyy-MM-dd";
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                String df = simpleDateFormat.format(dateFrom);
                String dt = simpleDateFormat.format(dateTo);

                //Procedure to call url
                //We pass the url to be called to a string
                String urlToCall = "https://api.opap.gr/draws/v3.0/5104/draw-date/" + df + "/" + dt + "/draw-id";
                OkHttpClient client = new OkHttpClient();

                Request request = new Request.Builder().url(urlToCall).build();

                //Call the appropriate url
                try (Response response = client.newCall(request).execute()) {
                    if (response.isSuccessful() && response.body() != null) {
                        String responseString = response.body().string();

                        //Process to extract the Json data
                        //Create a GsonBuilder object
                        GsonBuilder builder = new GsonBuilder();
                        Gson gson = builder.create();
                        //Get the results into a JsonArray
                        JsonArray json = gson.fromJson(responseString, JsonArray.class);

                        //Pass the data from JsonArray to GameIdComboBox
                        for (int i = 0; i < json.size(); i++) {
                            GameIdComboBox.addItem(json.get(i).toString());
                        }

                    } else {
                        //Informative message in case of incorrect date input (FromDate>ToDate)
                        JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή ημερομηνιών. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Πρόβλημα κλήσης URL. Προσπαθήστε ξανά.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } //If the user clicks search without having selected a date range then it displays an informational message
        else if (((FromDateComboBox.getSelectedItem() == null) || (ToDateComboBox.getSelectedItem() == null))) {
            //Informative message
            JOptionPane.showMessageDialog(null, "Πρέπει να εισάγετε ημερομηνίες. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SearchDateButtonActionPerformed

    private void deleteGameDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGameDataButtonActionPerformed
        //If the user has not entered a raffle code
        if ((GameIdComboBox1.getSelectedItem() == null)) {
            //Informative message
            JOptionPane.showMessageDialog(null, "Πρέπει να εισάγετε αριθμό κλήρωσης παιχνιδιού.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //Check if the entered draw to be deleted is in the correct format
        try {
            Integer.parseInt((String) GameIdComboBox1.getSelectedItem());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή δεδομένων.\nO αριθμός κλήρωσης αποτελείται μόνο από ακέραιους αριθμούς.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //Informative message to user
        int result = JOptionPane.showConfirmDialog(null, "Tο σύστημα θα διαγράψει από τη βάση δεδομένων τα δεδομένα της κλήρωσης με αριθμό " + GameIdComboBox1.getSelectedItem()
                + ".\nΕίστε σίγουροι;", "Διαγραφή Δεδομένων Κλήρωσης", JOptionPane.YES_NO_OPTION);

        //If the user confirms the deletion of the draw from the database
        if (JOptionPane.YES_OPTION == result) {
            System.out.println("ΑΠΟΔΟΧΗ ΔΙΑΓΡΑΦΗΣ");

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokerGameStatsPU");
            EntityManager em = emf.createEntityManager();

            //Attempt to start transaction with database to clear draw
            try {
                //Start transaction
                em.getTransaction().begin();
                //Delete records with the selected drawId, from database tables
                Query selectDraw = em.createNamedQuery("Draw.findById", Draw.class);
                selectDraw.setParameter("id", Integer.parseInt((String) GameIdComboBox1.getSelectedItem()));

                try {
                    Draw drawPj = (Draw) selectDraw.getSingleResult();
                    em.remove(drawPj);
                    //End transaction
                    em.getTransaction().commit();
                    //Informative message
                    JOptionPane.showMessageDialog(null, "Τα δεδομένα της κλήρωσης διαγράφηκαν επιτυχώς από τη βάση δεδομένων.", "Eνημέρωση", JOptionPane.INFORMATION_MESSAGE);

                } catch (NoResultException ex) {
                    //End transaction
                    em.getTransaction().commit();
                    //Informative message in case the lottery selected to be deleted does not exist
                    JOptionPane.showMessageDialog(null, "Η κλήρωση που επιλέξατε δεν είναι καταχωρημένη στη βάση δεδομένων.", "Eνημέρωση", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Η διαγραφή δεν ήταν επιτυχής. Προσπαθήστε ξανά.", "Σφάλμα", JOptionPane.INFORMATION_MESSAGE);
            }

            //Destroy EntityManagerFactory and EntityManager
            em.close();
            emf.close();
        }
        //If the user declines to delete the draw from the database nothing happens


    }//GEN-LAST:event_deleteGameDataButtonActionPerformed

    private void SearchDrawIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDrawIdButtonActionPerformed
        //Search result with lottery code

        //If the user presses search based on drawId but has not entered a drawId, a relevant message appears on the screen
        if ((GameIdComboBox.getSelectedItem() == null)) {
            //Informative message
            JOptionPane.showMessageDialog(null, "Πρέπει να εισάγετε αριθμό κλήρωσης παιχνιδιού.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        } else if ((GameIdComboBox.getSelectedItem() != null)) {

            //Call process url
            String urlToCall = "https://api.opap.gr/draws/v3.0/5104/" + GameIdComboBox.getSelectedItem().toString();
            OkHttpClient client = new OkHttpClient();

            Request request = new Request.Builder().url(urlToCall).build();

            try (Response response = client.newCall(request).execute()) {
                if (response.isSuccessful() && response.body() != null) {
                    String responseString = response.body().string();

                    //Process to extract the Json data
                    //Create a GsonBuilder object
                    GsonBuilder builder = new GsonBuilder();
                    builder.setPrettyPrinting();
                    Gson gson = builder.create();
                    //Create a JsonObject that contains the Json we extracted
                    JsonObject jsonObj = gson.fromJson(responseString, JsonObject.class);
                    //Create a JsonObject containing the JsonObject named winningNumbers
                    JsonObject winningNumbersObj = jsonObj.getAsJsonObject("winningNumbers");
                    //We create a JsonArray that takes as arguments the list containing the winningNumbers
                    JsonArray winningNumbers = winningNumbersObj.getAsJsonArray("list");
                    //Create a JsonArray that takes as arguments the contents of the JsonArray named bonus
                    JsonArray bonus = winningNumbersObj.getAsJsonArray("bonus");
                    //Create a JsonArray that takes as arguments the contents of the JsonArray named prizeCategories
                    JsonArray prizeCategories = jsonObj.getAsJsonArray("prizeCategories");
                    //We store in the drawId variable the draw number we got from the JsonObject
                    int drawId = jsonObj.get("drawId").getAsInt();
                    //Store in the drawTime variable the date and time that the draw took place, which we got from the JsonObject
                    long drawTime = jsonObj.get("drawTime").getAsLong();

                    //Procedure to view the data for a specific drawId(winningNumbers, winnings baseCategories
                    //and for each category we want:winners,dividend)
                    //Temporary storage of draw data
                    int[] winningNumbersArray = new int[6];
                    for (int i = 0; i < 6; i++) {
                        int winningNumber;
                        if (i <= 4) {
                            winningNumber = winningNumbers.get(i).getAsInt();
                        } else {
                            winningNumber = bonus.get(0).getAsInt();
                        }
                        winningNumbersArray[i] = winningNumber;

                    }

                    //Because we want the results of a draw to be displayed in the table every time we create a new object
                    draw.prizeCategories = new ArrayList<PrizeCategory>();

                    //Store the data we get from the json
                    for (int i = 0; i < prizeCategories.size(); i++) {
                        JsonObject prizeCategory = prizeCategories.get(i).getAsJsonObject();
                        int winners = prizeCategories.get(i).getAsJsonObject().get("winners").getAsInt();
                        double divident = prizeCategories.get(i).getAsJsonObject().get("divident").getAsDouble();

                        //If the lottery number is 1-209 then convert the drachmas to euros and round the result to 2 digits
                        //we consider that the then exchange value of the euro was 1EURO=340.75GRD
                        if (drawId >= 1 && drawId <= 209) {
                            divident = Math.round((divident / 340.75) * 100.0) / 100.0;
                        }
                        PrizeCategory prc = new PrizeCategory(prizeCategory.get("id").getAsInt(), drawId, winners, divident);

                        draw.setId(drawId);
                        draw.setDrawTime(drawTime);
                        draw.setWinningNumber1(winningNumbersArray[0]);
                        draw.setWinningNumber2(winningNumbersArray[1]);
                        draw.setWinningNumber3(winningNumbersArray[2]);
                        draw.setWinningNumber4(winningNumbersArray[3]);
                        draw.setWinningNumber5(winningNumbersArray[4]);
                        draw.setBonusNumber(bonus.get(0).getAsInt());
                        draw.addCategory(prc);
                    }
                    //Create a jframe DrawData object to display the results
                    DrawData drawData = new DrawData();
                    //Update resultTable of jframe DrawData
                    drawData.UpdateResultTable(draw);
                    drawData.updateDrawData(draw);

                    //Display the DrawData screen containing the array with the requested data
                    drawData.setVisible(true);
                } else {
                    //Notify user in case he enters wrong data or the entered draw does not exist
                    JOptionPane.showMessageDialog(null, "Η κλήρωση δεν υπάρχει. "
                            + "(Input= " + GameIdComboBox.getSelectedItem().toString() + ")", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Πρόβλημα κλήσης URL. Προσπαθήστε ξανά. "
                        + "(Input= " + GameIdComboBox.getSelectedItem().toString() + ")", "Σφάλμα", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_SearchDrawIdButtonActionPerformed

    private void ShowDataDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDataDateButtonActionPerformed
        //Search result with date range

        //If the user has entered dates
        if (((FromDateComboBox.getSelectedItem() != null) && (ToDateComboBox.getSelectedItem() != null))) {

            //Check if date is in correct format
            DateValidator validator = new DateValidatorUsingDateFormat("yyyy-mm-dd");
            if (!validator.isValid(FromDateComboBox.getSelectedItem().toString()) || !validator.isValid(ToDateComboBox.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "Οι ημερομηνίες δεν είναι σε σωστή μορφή (εεεε-μμ-ηη).", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            //Check if the entered dates are up to date
            //Check if the date is valid (eg 2022-02-30 is an invalid date)
            try {
                LocalDate fromDate = LocalDate.parse(FromDateComboBox.getSelectedItem().toString());
                LocalDate toDate = LocalDate.parse(ToDateComboBox.getSelectedItem().toString());

                //Check if the entered dates are up to date
                if (LocalDate.now().isBefore(fromDate) || LocalDate.now().isBefore(toDate)) {
                    JOptionPane.showMessageDialog(null, "Έχετε εισάγει ημερομηνίες που ξεπερνούν τη σημερινή ημέρα. Προσπαθήστε ξανά.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(null, "Μη έγκυρη ημερομηνία.", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            //We calculate from how many days the user chooses to get information from because he can get information up to 3 months (94 days)
            LocalDate fromDate = LocalDate.parse(FromDateComboBox.getSelectedItem().toString());
            LocalDate toDate = LocalDate.parse(ToDateComboBox.getSelectedItem().toString());
            long fromDateDays = fromDate.toEpochDay();
            long toDateDays = toDate.toEpochDay();
            long duration = toDateDays - fromDateDays + 1;

            //Informative message to the user in case the fromDate date is greater than the toDate date
            if (duration < 0) {
                JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή εύρους ημερομηνιών. Προσπαθήστε ξανά. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            //Initialize the timezone because we will need it in date conversions
            ZoneId defaultZoneId = ZoneId.systemDefault();
            //Create a list of Draw objects to store the data we pull from the json
            ArrayList<Draws> draws = new ArrayList<>();
            //If the date range entered by the user exceeds 94 days
            //url returns no data
            //So we "break" the dates into chunks and call the url to fetch data per "chunk"
            while (duration > 94) {
                toDate = fromDate.plusDays(93);
                Date dateTo = Date.from(toDate.atStartOfDay(defaultZoneId).toInstant());
                Date dateFrom = Date.from(fromDate.atStartOfDay(defaultZoneId).toInstant());
                String pattern = "yyyy-MM-dd";
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                String df = simpleDateFormat.format(dateFrom);
                String dt = simpleDateFormat.format(dateTo);

                //Procedure to call url
                //We pass the url to be called to a string
                String urlToCall = "https://api.opap.gr/draws/v3.0/5104/draw-date/" + df + "/" + dt + "/?limit=200";
                OkHttpClient client = new OkHttpClient();

                Request request = new Request.Builder().url(urlToCall).build();

                //Call the appropriate url
                try (Response response = client.newCall(request).execute()) {
                    if (response.isSuccessful() && response.body() != null) {
                        String responseString = response.body().string();

                        //Process to extract the Json data
                        //Create a GsonBuilder object
                        GsonBuilder builder = new GsonBuilder();
                        Gson gson = builder.create();
                        //Create a JsonObject that contains the Json we extracted
                        JsonObject jsonObj = gson.fromJson(responseString, JsonObject.class);
                        //Create a JsonArray containing the Objects
                        JsonArray content = jsonObj.getAsJsonArray("content");

                        //We extract the desired data from json and pass it to objects of type Draw
                        for (JsonElement draw : content) {
                            int drawId = draw.getAsJsonObject().get("drawId").getAsInt();
                            long drawTime = draw.getAsJsonObject().get("drawTime").getAsLong();
                            JsonArray winningNumbers = draw.getAsJsonObject().get("winningNumbers").getAsJsonObject().get("list").getAsJsonArray();
                            JsonArray bonusNumbers = draw.getAsJsonObject().get("winningNumbers").getAsJsonObject().get("bonus").getAsJsonArray();
                            JsonArray prizeCategories = draw.getAsJsonObject().get("prizeCategories").getAsJsonArray();
                            Draws drawObj = new Draws(drawId, drawTime);
                            drawObj.setWinningNumber1(winningNumbers.get(0).getAsInt());
                            drawObj.setWinningNumber2(winningNumbers.get(1).getAsInt());
                            drawObj.setWinningNumber3(winningNumbers.get(2).getAsInt());
                            drawObj.setWinningNumber4(winningNumbers.get(3).getAsInt());
                            drawObj.setWinningNumber5(winningNumbers.get(4).getAsInt());
                            drawObj.setBonusNumber(bonusNumbers.get(0).getAsInt());
                            drawObj.setDrawTime(drawTime);

                            // We extract the desired data from the json and pass it to objects of type PrizeCategory
                            for (JsonElement prizeCategory : prizeCategories) {
                                double divident = prizeCategory.getAsJsonObject().get("divident").getAsDouble();
                                int winners = prizeCategory.getAsJsonObject().get("winners").getAsInt();
                                int prizeCategoryId = prizeCategory.getAsJsonObject().get("id").getAsInt();
                                PrizeCategory prizeCategoryObj = new PrizeCategory(prizeCategoryId, drawId, winners, divident);

                                drawObj.addCategory(prizeCategoryObj);
                            }
                            draws.add(drawObj);
                        }

                        //Calculate the new dates for which Url will be called
                        duration = duration - 94;
                        fromDate = toDate.plusDays(1);
                        if (duration == 0) {
                            break;
                        } else if (duration < 95) {
                            toDate = toDate.plusDays(duration);
                        }

                    } else {
                        //Informative message in case of incorrect date input (FromDate>ToDate)
                        JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή ημερομηνιών. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Πρόβλημα κλήσης URL. Προσπαθήστε ξανά.", "Σφάλμα", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            //If there are days left when we didn't pull data recalculate dates and callback url
            if (duration > 0 && duration < 95) {
                Date dateTo = Date.from(toDate.atStartOfDay(defaultZoneId).toInstant());
                Date dateFrom = Date.from(fromDate.atStartOfDay(defaultZoneId).toInstant());
                String pattern = "yyyy-MM-dd";
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                String df = simpleDateFormat.format(dateFrom);
                String dt = simpleDateFormat.format(dateTo);

                //Procedure to call url
                //We pass the url to be called to a string
                String urlToCall = "https://api.opap.gr/draws/v3.0/5104/draw-date/" + df + "/" + dt + "/?limit=200";
                OkHttpClient client = new OkHttpClient();

                Request request = new Request.Builder().url(urlToCall).build();

                //Call the appropriate url
                try (Response response = client.newCall(request).execute()) {
                    if (response.isSuccessful() && response.body() != null) {
                        String responseString = response.body().string();

                        //Process to extract the Json data
                        //Create a GsonBuilder object
                        GsonBuilder builder = new GsonBuilder();
                        Gson gson = builder.create();
                        //Create a JsonObject that contains the Json we extracted
                        JsonObject jsonObj = gson.fromJson(responseString, JsonObject.class);

                        //Create a JsonArray containing the Objects
                        JsonArray content = jsonObj.getAsJsonArray("content");

                        //We extract the desired data from the json and pass it to objects of type Draw
                        for (JsonElement draw : content) {
                            int drawId = draw.getAsJsonObject().get("drawId").getAsInt();
                            long drawTime = draw.getAsJsonObject().get("drawTime").getAsLong();
                            JsonArray winningNumbers = draw.getAsJsonObject().get("winningNumbers").getAsJsonObject().get("list").getAsJsonArray();
                            JsonArray bonusNumbers = draw.getAsJsonObject().get("winningNumbers").getAsJsonObject().get("bonus").getAsJsonArray();
                            JsonArray prizeCategories = draw.getAsJsonObject().get("prizeCategories").getAsJsonArray();
                            Draws drawObj = new Draws(drawId, drawTime);
                            drawObj.setWinningNumber1(winningNumbers.get(0).getAsInt());
                            drawObj.setWinningNumber2(winningNumbers.get(1).getAsInt());
                            drawObj.setWinningNumber3(winningNumbers.get(2).getAsInt());
                            drawObj.setWinningNumber4(winningNumbers.get(3).getAsInt());
                            drawObj.setWinningNumber5(winningNumbers.get(4).getAsInt());
                            drawObj.setBonusNumber(bonusNumbers.get(0).getAsInt());
                            drawObj.setDrawTime(drawTime);

                            //We extract the required data from the json and pass it to objects of type PrizeCategory
                            for (JsonElement prizeCategory : prizeCategories) {
                                double divident = prizeCategory.getAsJsonObject().get("divident").getAsDouble();
                                int winners = prizeCategory.getAsJsonObject().get("winners").getAsInt();
                                int prizeCategoryId = prizeCategory.getAsJsonObject().get("id").getAsInt();
                                PrizeCategory prizeCategoryObj = new PrizeCategory(prizeCategoryId, drawId, winners, divident);

                                drawObj.addCategory(prizeCategoryObj);
                            }
                            draws.add(drawObj);
                        }

                    } else {
                        //Informative message in case of incorrect date input (FromDate>ToDate)
                        JOptionPane.showMessageDialog(null, "Λάθος εισαγωγή ημερομηνιών. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Πρόβλημα κλήσης URL. Προσπαθήστε ξανά.", "Σφάλμα", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            //Create a jframe in which to display the results
            DynamicDrawData dynamicDrawData = new DynamicDrawData();
            //Update the table to be displayed in the draw data view jframe dynamicDrawData
            dynamicDrawData.updateTables(draws);
            //Make visible the jframe dynamicDrawData display of draw data
            dynamicDrawData.setVisible(true);

        } //If the user clicks search without having selected a date range then it displays an informational message
        else if (((FromDateComboBox.getSelectedItem() == null) || (ToDateComboBox.getSelectedItem() == null))) {
            //Informative message
            JOptionPane.showMessageDialog(null, "Πρέπει να εισάγετε ημερομηνίες. ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ShowDataDateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new ManageData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FromDateComboBox;
    private javax.swing.JComboBox<String> FromDateComboBox1;
    private javax.swing.JComboBox<String> GameIdComboBox;
    private javax.swing.JComboBox<String> GameIdComboBox1;
    private javax.swing.JButton SearchDateButton;
    private javax.swing.JButton SearchDrawIdButton;
    private javax.swing.JButton ShowDataDateButton;
    private javax.swing.JComboBox<String> ToDateComboBox;
    private javax.swing.JComboBox<String> ToDateComboBox1;
    private javax.swing.JLabel backgroundLayer;
    private javax.swing.JButton deleteGameDataButton;
    private javax.swing.JButton deleteGameDataFromDateToDateButton;
    private javax.swing.JLabel fromDateLabel;
    private javax.swing.JLabel fromDateLabel1;
    private javax.swing.JLabel gameIdLabel;
    private javax.swing.JLabel gameIdLabel1;
    private javax.swing.JLabel manageDataLabel;
    private javax.swing.JButton returnHomeButton;
    private javax.swing.JLabel toDateLabel;
    private javax.swing.JLabel toDateLabel1;
    // End of variables declaration//GEN-END:variables
}
