/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import pojo.Draw;
import pojo.Prizecategory;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @authors Lymperis Dimitrios 
 *          Papaioannou Emmanolia 
 *          Chatziioannou Ioannis
 */
public class ShowDataPerMonth extends javax.swing.JFrame {

    /**
     * Creates new form ShowDataPerMonth
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ShowDataPerMonth() {
        initComponents();
        setTitle("JokerGame-Stats");
        //Βοηθητικό comboBox για αποθήκευση των μηνών ως αριθμούς.
        invisibleComboBox.setVisible(false);
        comboYears();

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                super.windowClosing(we);
            }
        });
    }

    //Method that converts an integer month number to a string with the name of the month
    private String getMonth(int month) {
        String[] nameMonth = {"Ιανουάριος", "Φεβρουάριος", "Μάρτιος", "Απρίλιος",
            "Μάϊος", "Ιούνιος", "Ιούλιος", "Αύγουστος", "Σεπτέμβριος", "Οκτώβριος", "Νοέμβριος", "Δεκέμβριος"};
        return nameMonth[month - 1];
    }

    //Method that fills the ComboYearBox with the years stored in the database
    private void comboYears() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokerGameStatsPU");
        EntityManager em = emf.createEntityManager();
        //Selects the year from the Date column of the Draw table (groups dates with the same year)
        //from the date and stores it in an array in ascending order
        Query selectDate = em.createNativeQuery("SELECT YEAR(DATE) AS YEARS FROM DRAW GROUP BY YEAR(DATE)");
        Object[] result = selectDate.getResultList().toArray();
        //Iterate through the result array and add the years to the jComboYearBox
        for (Object results : result) {
            comboYearBox.addItem(results.toString());
        }
        //Destroy EntityManager and EntityManagerFactory
        em.close();
        emf.close();
    }

    //Method that fills the ComboMonthBox with the months stored in the database, for a selected year
    private void comboMonths() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokerGameStatsPU");
        EntityManager em = emf.createEntityManager();
        //From the Date column of the Draw table selects the months
        //from the date and stores it in an array in ascending order
        String year = comboYearBox.getSelectedItem().toString();
        Query selectDate = em.createNativeQuery("SELECT MONTH(DATE) AS MONTHS FROM DRAW WHERE YEAR(DATE)=" + year + " GROUP BY MONTH(DATE)");
        Object[] result = selectDate.getResultList().toArray();
        ArrayList<Integer> month = new ArrayList<>();
        //It goes through the table result and its elements are stored in the table month
        //by converting them to Integer
        for (Object results : result) {
            month.add((Integer) results);
            invisibleComboBox.addItem(results.toString());
        }
        //For each number contained in the month array, store in the comboMonthBox the name
        //of the corresponding month using the getMonth method
        for (int i = 0; i < month.size(); i++) {
            comboMonthBox.addItem(this.getMonth(month.get(i)));
        }
        //Destroy EntityManager and EntityManagerFactory
        em.close();
        emf.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnHomeButton = new javax.swing.JButton();
        showDataLabel = new javax.swing.JLabel();
        comboYearBox = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        comboMonthBox = new javax.swing.JComboBox<>();
        SearchMonthButton = new javax.swing.JButton();
        invisibleComboBox = new javax.swing.JComboBox<>();
        backgroundLayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(571, 429));
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1_1.png"))); // NOI18N
        returnHomeButton.setBorder(null);
        returnHomeButton.setBorderPainted(false);
        returnHomeButton.setContentAreaFilled(false);
        returnHomeButton.setFocusPainted(false);
        returnHomeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1click.png"))); // NOI18N
        returnHomeButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1click.png"))); // NOI18N
        returnHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        showDataLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showDataLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        showDataLabel.setText("Προβολή δεδομένων ");
        getContentPane().add(showDataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 50));

        comboYearBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboYearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Επιλογή" }));
        comboYearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearBoxActionPerformed(evt);
            }
        });
        getContentPane().add(comboYearBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        yearLabel.setText("Έτος:");
        yearLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        getContentPane().add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, 20));

        monthLabel.setText("Μήνας:");
        monthLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        getContentPane().add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 20));

        comboMonthBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(comboMonthBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        SearchMonthButton.setBackground(new java.awt.Color(49, 144, 226));
        SearchMonthButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchMonthButton.setText("Αναζήτηση");
        SearchMonthButton.setForeground(new java.awt.Color(0, 0, 0));
        SearchMonthButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMonthButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchMonthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 80, -1));

        getContentPane().add(invisibleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        backgroundLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tzoker_image2.jpg"))); // NOI18N
        backgroundLayer.setText("jLabel1");
        backgroundLayer.setFocusCycleRoot(true);
        backgroundLayer.setPreferredSize(new java.awt.Dimension(570, 429));
        getContentPane().add(backgroundLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(ShowDataPerMonth.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_returnHomeButtonActionPerformed

    private void SearchMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMonthButtonActionPerformed
        if (comboYearBox.getSelectedIndex() != 0) {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokerGameStatsPU");
            EntityManager em = emf.createEntityManager();

            //Helper variables to calculate and store the aggregated data
            int countDraws;
            double countTotalDivident;
            int countJackpot;
            String year = comboYearBox.getSelectedItem().toString();
            String month = comboMonthBox.getSelectedItem().toString();
            invisibleComboBox.setSelectedIndex(comboMonthBox.getSelectedIndex());
            String month1 = invisibleComboBox.getSelectedItem().toString();

            //Create an appropriate query to the database
            Query selectDate = em.createNativeQuery("SELECT * FROM DRAW WHERE YEAR(DATE) = " + year + " AND MONTH(DATE) = " + month1, Draw.class);
            //We get the database results into a list
            List<Draw> drawsPj = selectDate.getResultList();

            //Calculate number of draws
            countDraws = drawsPj.size();

            //Calculate a number of distributed profits
            countTotalDivident = 0;
            double countDividentPerCategory;


            for (Draw draw : drawsPj) {
                //List the 8 win categories per draw
                List<Prizecategory> prizeCategory = draw.getPrizecategoryList();
                for (Prizecategory prizeCategories : prizeCategory) {
                    //Calculate per success category how much money was distributed
                    countDividentPerCategory = prizeCategories.getDivident() * prizeCategories.getWinners();
                    //We calculate the total amount of money distributed
                    countTotalDivident += countDividentPerCategory;
                }
            }

            //Calculate jackpot count
            countJackpot = 0;
            for (Draw draw : drawsPj) {
                //List the 8 win categories per draw
                List<Prizecategory> prizeCategory = draw.getPrizecategoryList();
                //If there was no winner in the 5+1 category then it became jackpot
                if (prizeCategory.get(0).getWinners() == 0) {
                    countJackpot++;
                }
                //If there was no winner in category 5 then it became jackpot
                if (prizeCategory.get(1).getWinners() == 0) {
                    countJackpot++;
                }
            }

            //Destroy EntityManager and EntityManagerFactory
            em.close();
            emf.close();

            NumberFormat formatter = NumberFormat.getCurrencyInstance();
            String moneyString = formatter.format(countTotalDivident);

            //Create a jframe in which to display the results
            ShowDataPerMonthFinal showDataPerMonthFinal = new ShowDataPerMonthFinal();
            showDataPerMonthFinal.setVisible(true);
            //Update the showDataPerMonthFinal table with the aggregated data
            showDataPerMonthFinal.updateShowDataTable(countDraws, moneyString, countJackpot);
            //Update the showDataPerMonthFinal label with the month and year of the user's choice
            showDataPerMonthFinal.updateDateLabel(month, year);
            //Make the ShowDataPerMonth window not visible
            this.setVisible(false);
            this.setDefaultCloseOperation(ShowDataPerMonth.EXIT_ON_CLOSE);
            this.dispose();
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }

    }//GEN-LAST:event_SearchMonthButtonActionPerformed

    private void comboYearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearBoxActionPerformed
        if (comboYearBox.getSelectedIndex() != 0) {
            //Every time the year selection changes the months of the previous selection are removed
            comboMonthBox.removeAllItems();
            invisibleComboBox.removeAllItems();
            //Fill the comboBox with the months stored for each year
            comboMonths();
        } else {
            comboMonthBox.removeAllItems();
        }

    }//GEN-LAST:event_comboYearBoxActionPerformed

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(null, //Eνημερωτικό μήνυμα όταν ο χρήστης κλείνει την εφαρμογή
                "Η εφαρμογή θα τερματιστεί. Είστε σίγουροι;", "Τερματισμός εφαρμογής",
                JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ShowDataPerMonth().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchMonthButton;
    private javax.swing.JLabel backgroundLayer;
    private javax.swing.JComboBox<String> comboMonthBox;
    private javax.swing.JComboBox<String> comboYearBox;
    private javax.swing.JComboBox<String> invisibleComboBox;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton returnHomeButton;
    private javax.swing.JLabel showDataLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
