/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @authors Lymperis Dimitrios
 *          Papaioannou Emmanolia
 *          Chatziioannou Ioannis
 */
public class ShowDataPerMonthFinal extends javax.swing.JFrame {

    /**
     * Creates new form ShowDataPerMonthFinal
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ShowDataPerMonthFinal() {
        initComponents();
        setTitle("JokerGame-Stats");
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                super.windowClosing(we);
            }
        });
    }

    //Method that updates jframe's monthTextField with date and year
    public void updateDateLabel(String month, String year){
        monthTextField.setHorizontalAlignment(JTextField.CENTER);
        monthTextField.setText(month+"  "+year);
    }

    //Method to create arrays with draws data
    public void updateShowDataTable(int countDraws, String countTotalDivident, int countJackpot) {
        DefaultTableModel model=(DefaultTableModel) showDataTable.getModel();
        Object[] rowValues = {countDraws, countTotalDivident, countJackpot};
        model.addRow(rowValues);
        showDataPane.getViewport().add(showDataTable);
        showDataTable.setAutoCreateRowSorter(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showDataLabel = new javax.swing.JLabel();
        jHomeButton = new javax.swing.JButton();
        showDataPane = new javax.swing.JScrollPane();
        showDataTable = new javax.swing.JTable();
        monthTextField = new JTextField();
        returnButton = new javax.swing.JButton();
        backgroundLayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 405));
        setResizable(false);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showDataLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showDataLabel.setForeground(new java.awt.Color(222, 222, 222)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        showDataLabel.setText("Προβολή συγκεντρωτικών δεδομένων μήνα ");
        getContentPane().add(showDataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 390, 50));

        jHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1_1.png"))); // NOI18N
        jHomeButton.setBorder(null);
        jHomeButton.setBorderPainted(false);
        jHomeButton.setContentAreaFilled(false);
        jHomeButton.setFocusPainted(false);
        jHomeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1click.png"))); // NOI18N
        jHomeButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_image1click.png"))); // NOI18N
        jHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        showDataPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        showDataPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        showDataTable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        showDataTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Πλήθος παιχνιδιών", "Διανεμόμενα Χρήματα", "Πλήθος ΤΖΑΚΠΟΤ"
            }
        ));
        showDataPane.setViewportView(showDataTable);
        showDataTable.getAccessibleContext().setAccessibleName("");

        getContentPane().add(showDataPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 370, 40));

        monthTextField.setEditable(false);
        monthTextField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        monthTextField.setForeground(new java.awt.Color(0, 0, 0)); //Αλλαγή χρώμα γραμμάτων σε λευκό
        monthTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        monthTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthTextField.setBackground(new java.awt.Color(49, 144, 226));
        getContentPane().add(monthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 30));

        returnButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        returnButton.setBackground(new java.awt.Color(49, 144, 226));
        returnButton.setForeground(new java.awt.Color(0, 0, 0));
        returnButton.setText("<<  Επιστροφή");
        returnButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnButton.setContentAreaFilled(false);
        returnButton.setOpaque(true);
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, 30));

        backgroundLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tzoker_image2.jpg"))); // NOI18N
        backgroundLayer.setText("jLabel1");
        backgroundLayer.setFocusCycleRoot(true);
        backgroundLayer.setPreferredSize(new java.awt.Dimension(570, 429));
        getContentPane().add(backgroundLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        ShowDataPerMonth showDataPerMonth = new ShowDataPerMonth();
        showDataPerMonth.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(ShowDataPerMonthFinal.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(null, //Eνημερωτικό μήνυμα όταν ο χρήστης κλείνει την εφαρμογή
                        "Η εφαρμογή θα τερματιστεί. Είστε σίγουροι;", "Τερματισμός εφαρμογής",
                        JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomeButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(ShowDataPerMonthFinal.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jHomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonthFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonthFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonthFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowDataPerMonthFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ShowDataPerMonthFinal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLayer;
    private javax.swing.JButton jHomeButton;
    private JTextField monthTextField;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel showDataLabel;
    private javax.swing.JScrollPane showDataPane;
    private javax.swing.JTable showDataTable;
    // End of variables declaration//GEN-END:variables
}
