/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import org.emmapap.ChartData;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.title.TextTitle;
import org.jfree.chart.ui.HorizontalAlignment;
import org.jfree.chart.ui.RectangleEdge;
import org.jfree.data.category.DefaultCategoryDataset;

import java.util.List;

/**
 *
 * @authors Papaioannou Emmanolia 
 *          Lymperis Dimitrios
 *          Chatziioannou Ioannis 
 */
public class StatisticsGraphicForm extends javax.swing.JFrame {

    /**
     * Creates new form StatisticsGraphicForm
     */
    public StatisticsGraphicForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraphicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraphicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraphicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraphicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsGraphicForm().setVisible(true);
            }
        });
    }

    //Graph creation method for number displays and number wildcards
    public void plotChart(String chartTitle, String xTitle, String yTitle, List<ChartData> data) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (ChartData d : data) {
            dataset.addValue((int) d.y, "Πλήθος εμφανίσεων αριθμού", String.valueOf((int) d.x));
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                chartTitle,
                xTitle, yTitle,
                dataset, PlotOrientation.HORIZONTAL,
                true, true, false);

        ChartFrame frame = new ChartFrame(chartTitle, barChart);
        frame.setVisible(true);
        frame.setSize(500, 500);

        //Add note to chart
        TextTitle chartInfo = new TextTitle("Δεξί κλικ πάνω στο γράφημα για εμφάνιση ρυθμίσεων.");
        barChart.addSubtitle(chartInfo);
        chartInfo.setPosition(RectangleEdge.BOTTOM);
        chartInfo.setHorizontalAlignment(HorizontalAlignment.CENTER);
        chartInfo.setTextAlignment(HorizontalAlignment.CENTER);
    }

    //Method to create graph for average earnings per category
    public void plotAvgChart(String chartTitle, String xTitle, String yTitle, List<ChartData> data) {

        final String[] x = {"5+1", "5", "4+1", "4", "3+1", "3", "2+1", "1+1"};
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        int i = 0;
        for (ChartData d : data) {
            dataset.addValue(d.y, "Κατηγορία επιτυχίας", x[i]);
            i++;
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                chartTitle,
                xTitle, yTitle,
                dataset, PlotOrientation.VERTICAL,
                true, true, false);

        ChartFrame frame = new ChartFrame(chartTitle, barChart);
        frame.setVisible(true);
        frame.setSize(500, 500);

        //Add note to chart
        TextTitle chartInfo = new TextTitle("Πατήστε και σύρετε με το ποντίκι φτιάχνοντας ένα ορθογώνιο με κατεύθυνση προς τα κάτω, για να κάνετε zoom στην επιθυμητή περιοχή.");
        barChart.addSubtitle(chartInfo);
        chartInfo.setPosition(RectangleEdge.BOTTOM);
        chartInfo.setHorizontalAlignment(HorizontalAlignment.CENTER);
        chartInfo.setTextAlignment(HorizontalAlignment.CENTER);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
